---
kind: pipeline
name: Lint
type: docker
steps:
  - name: Lint
    image: harryuan65/rubocop-docker:1.42.0-amd64
    environment:
      BUNDLE_GEMFILE: /linter/Gemfile.linter
    commands:
      - bundle exec rubocop -v
      - bundle exec rubocop
---
# drone exec  --pipeline Testing --trusted
kind: pipeline
type: docker
name: Testing
steps:
  - name: Test
    image: harryuan65/rspec-docker:1.0
    volumes:
      - name: gems
        path: /tmp/gems
    environment:
      RAILS_ENV: test
      RAKE_ENV: test
      REDIS_URL: redis://redis:6379/0
      PG_HOST: database
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
    commands:
      - bundle config set --local without 'production,development'
      - echo "-----------------------------------------"
      - ls /tmp/gems/ruby
      - echo "-----------------------------------------"
      - |
        if [ -d /tmp/gems ]; then
          bundle config set --local path /tmp/gems
          bundle install
        else
          bundle config set --local path vendor/bundle
          bundle install --jobs 4
        fi
      - bundle exec rails db:create
      - bundle exec rails db:schema:load
      - bundle exec rspec
    depends_on:
      - database
      - redis
services:
  - name: database
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - name: pg
        path: /var/lib/postgresql/data
  - name: redis
    image: redis:7.0.4-alpine
volumes:
  - name: gems
    host:
      path: /tmp/gems
  - name: pg
    host:
      path: /tmp/data/postgres
