---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  schemas:
    to_do_item:
      type: object
      properties:
        title:
          type: string
        status:
          type: string
          enum:
          - active
          - done
      required:
      - title
      - status
paths:
  "/to_do_items":
    get:
      summary: List to_do_items
      tags:
      - ToDoItem
      responses:
        '200':
          description: Successfully received list of to_do_items
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/to_do_item"
    post:
      summary: Create to_do_item
      tags:
      - ToDoItem
      parameters: []
      responses:
        '200':
          description: Successfully created to_do_item
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/to_do_item"
        required: true
        description: to_do_item fields
  "/to_do_items/{id}":
    patch:
      summary: Update to_do_item
      tags:
      - ToDoItem
      parameters:
      - name: id
        in: path
        required: true
        description: to_do_item id
        schema:
          type: integer
      responses:
        '204':
          description: Update success
        '404':
          description: Not found
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/to_do_item"
        required: true
        description: to_do_item fields
    delete:
      summary: Delete to_do_item
      tags:
      - ToDoItem
      parameters:
      - name: id
        in: path
        required: true
        description: to_do_item id
        schema:
          type: integer
      responses:
        '204':
          description: Delete success
        '404':
          description: Not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
